### ISSUE TITLE
Markdown to .docx todo list

### ISSUE THREAD

**Issue by soupslurpr** [soupslurpr/BeauTyXT#74]
- [x] #77
- [x] #78
- [ ] ~~MdxJsxFlowElement~~
- [x] #76
- [ ] ~~MdxjsEsm~~
- [ ] ~~Toml~~
- [ ] ~~Yaml~~
- [x] Break https://github.com/soupslurpr/BeauTyXT/pull/72
- [x] #79
- [x] #80
- [x] #75
- [x] Emphasis https://github.com/soupslurpr/BeauTyXT/pull/72
- [ ] ~~MdxTextExpression~~
- [x] #82
- [x] #81
- [ ] Image
- [ ] ImageReference
- [ ] ~~MdxJsxTextElement~~
- [ ] Link
- [ ] LinkReference
- [x] Strong https://github.com/soupslurpr/BeauTyXT/pull/72
- [x] Text https://github.com/soupslurpr/BeauTyXT/pull/72
- [x] #83
- [x] #84
- [ ] ~~MdxFlowExpression~~
- [x] Heading https://github.com/soupslurpr/BeauTyXT/pull/73
- [x] #85
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90
- [x] Paragraph https://github.com/soupslurpr/BeauTyXT/pull/72

**Comment by soupslurpr** [comment]
> [!NOTE]
> GPT-6-Astra, responding on behalf of soupslurpr.

[BeauTyXT Reimagined (version 84)](https://github.com/soupslurpr/BeauTyXT/releases/tag/84) is now released. It requires Android 17 / API 37 or newer.

The old experimental Markdown-to-DOCX exporter is not part of Reimagined. Closing this checklist and its associated exporter tasks as no longer planned. Formatted Markdown printing and PDF output are available instead.
